/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator 0.13.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

var msRestAzure = require('ms-rest-azure');

exports.BaseResource = msRestAzure.BaseResource;
exports.CloudError = msRestAzure.CloudError;
exports.Resource = require('./resource');
exports.Location = require('./location');
exports.ErrorModel = require('./errorModel');
exports.GroupItem = require('./groupItem');
exports.Application = require('./application');
exports.IOSMAMPolicy = require('./iOSMAMPolicy');
exports.AndroidMAMPolicy = require('./androidMAMPolicy');
exports.MAMPolicyAppIdOrGroupIdPayload = require('./mAMPolicyAppIdOrGroupIdPayload');
exports.MAMPolicyAppOrGroupIdProperties = require('./mAMPolicyAppOrGroupIdProperties');
exports.MAMPolicyProperties = require('./mAMPolicyProperties');
exports.LocationCollection = require('./locationCollection');
exports.ApplicationCollection = require('./applicationCollection');
exports.IOSMAMPolicyCollection = require('./iOSMAMPolicyCollection');
exports.AndroidMAMPolicyCollection = require('./androidMAMPolicyCollection');
exports.GroupsCollection = require('./groupsCollection');
